### ISSUE TITLE
new code

### ISSUE THREAD

**Issue by JaberChowdhury** [rifatalam240/practice-work#1]
html
``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="./style.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>new year offer</title>
  </head>
  <body>
    <header>
      <div class="header-section">
        <div class="header-title">
          <p>Happy New Year</p>
          <h1>
            New Year Party <br />
            Celebration
          </h1>
        </div>
        <img
          width="1320px"
          height="600px"
          src="./assets/images/Banner Image.png"
          alt="Banner"
        />
      </div>
    </header>
    <main>
      <section class="price-off">
        <h1>65% OFF</h1>
        <h6>OUR HOLIDAY DEALS ARE BETTER</h6>
        <h2>ALL CATEGORIES</h2>
        <img src="./assets/images/New Year Photo.png" alt="New Year Photo" />
      </section>
      <section>
        <div class="midnight">
          <div>
            <h1>
              Welcome to <br />
              midnight party
            </h1>
            <p>
              Dolor sit amet consectetur. Consequat eget consectetur maecenas
              sed molestie malesuada. Ipsum sed sodales risus ut pellentesque
              vel euismod.
            </p>
            <h4>JOIN NOW</h4>
          </div>
          <img
            width="319.83px"
            height="464.66px"
            src="./assets/images/Group 70.png"
            alt="Group 70.png"
          />
        </div>
      </section>
      <section>
        <div class="event-time">
          <p><span> Place:</span> New Park Hotel</p>
          <p><span> Date:</span> 31 December Night 2023</p>
          <p><span> Time:</span> Evening 7.30 pm to 12.30 am</p>
          <button>Join Now</button>
        </div>
      </section>
    </main>
  </body>
</html>
```

css
``` css
@import url("https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap");

body {
  margin: 0;
  padding: 0;
  padding-top: 30px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  position: relative;
  font-family: "Inter", serif;
  font-optical-sizing: auto;
  font-style: normal;
  box-sizing: border-box;
}
main {
  width: 100%;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  position: relative;
}
main > section {
  margin: 40px 0 40px 0;
  position: relative;
}
.header-section {
  position: relative;
  border-radius: 10px;
  overflow: hidden;
  font-family: "Merriweather", serif;
}
.header-title {
  width: 100%;
  height: 100%;
  z-index: 100;
  font-size: 15px;
  color: rgb(255, 255, 255);
  position: absolute;
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  background: -webkit-linear-gradient(
    top,
    rgb(0, 0, 0),
    rgba(255, 255, 255, 0)
  );
}
.header-title > p {
  font-size: 32px;
  line-height: auto;
}
.header-title > h1 {
  font-size: 72px;
}
.price-off > * {
  text-align: center;
  font-size: 88;
  line-height: 0%;
}
.price-off > h1 {
  color: red;
  font: bold;
  font-size: 88px;
  line-height: 90px;
}
.price-off > h6 {
  font-size: 24px;
}

.price-off > h2 {
  font-size: 48px;
}

.midnight {
  font-family: "Merriweather", serif;
  width: 100%;
  background-image: -webkit-linear-gradient(
      left,
      rgb(0, 0, 0),
      rgba(255, 255, 255, 0)
    ),
    url("./assets/images/Vectorrr.png");
  color: aliceblue;
  display: flex;
  justify-content: center;
  align-items: center;
  background-repeat: no-repeat;
  background-size: cover;
  padding: 60px;
  border-radius: 20px;
  margin: auto;
}
.midnight > div > h1 {
  font-size: 64px;
}
.midnight > div > p {
  font-size: 18px;
  width: 697px;
}
.midnight > div > h4 {
  font-size: 20px;
}

.event-time {
  width: 1320px;
  height: 480px;
  background: -webkit-linear-gradient(
    top,
    rgba(255, 0, 0, 0.279),
    rgba(255, 255, 255, 0)
  );
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  font-weight: bold;
  font-size: 32px;
  border-radius: 10px;
}
.event-time > p > span {
  color: red;
}
.event-time > p {
  line-height: 0%;
}
.event-time > button {
  width: 167px;
  height: 56px;
  font-size: 20px;
  font-weight: bold;
  color: white;
  outline: none;
  border: none;
  background-color: red;
  border-radius: 5px;
  margin: 60px;
}

```
